
import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CardNum_error = new javax.swing.JLabel();
        Date_error = new javax.swing.JLabel();
        CCV_error = new javax.swing.JLabel();
        CardHolder_error = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Card_holder_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Year = new javax.swing.JTextField();
        Card_number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ccv = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        payment = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(239, 234, 230));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 63, 63));
        jLabel1.setText("Check Out");

        back.setBackground(new java.awt.Color(130, 129, 90));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(209, 203, 198));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(331, 51));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-48 (1).png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(35, 35));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-heart-50.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(35, 35));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-bell-60.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(35, 35));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-60.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(150, 149, 104));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Card_holder_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card_holder_nameMouseClicked(evt);
            }
        });
        Card_holder_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card_holder_nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(63, 63, 63));
        jLabel3.setText("CCV:");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(63, 63, 63));
        jLabel6.setText("Card Number:");

        Year.setText("YYYY");
        Year.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YearMouseClicked(evt);
            }
        });
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });

        Card_number.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card_numberMouseClicked(evt);
            }
        });
        Card_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card_numberActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(76, 76, 76));
        jLabel4.setText("\\");

            ccv.setText("###");
            ccv.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    ccvMouseClicked(evt);
                }
            });
            ccv.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ccvActionPerformed(evt);
                }
            });

            jRadioButton1.setBackground(new java.awt.Color(150, 149, 104));
            jRadioButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
            jRadioButton1.setForeground(new java.awt.Color(76, 76, 76));
            jRadioButton1.setText("Save Card info");

            jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(63, 63, 63));
            jLabel2.setText("Exp.date:");

            month.setText("MM");
            month.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    monthMouseClicked(evt);
                }
            });

            payment.setBackground(new java.awt.Color(231, 214, 214));
            payment.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
            payment.setText("Confirm Payment");
            payment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            payment.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    paymentActionPerformed(evt);
                }
            });

            jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(63, 63, 63));
            jLabel7.setText("Card holder Name:");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Card_number, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ccv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(payment))
                        .addComponent(Card_holder_name, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(92, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Card_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(24, 24, 24)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Card_holder_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(ccv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(payment)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/paid.png"))); // NOI18N
            jLabel12.setPreferredSize(new java.awt.Dimension(48, 48));

            javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
            MainPanel.setLayout(MainPanelLayout);
            MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainPanelLayout.createSequentialGroup()
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(back))
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(MainPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(119, Short.MAX_VALUE))
                .addGroup(MainPanelLayout.createSequentialGroup()
                    .addComponent(Date_error)
                    .addGap(0, 0, 0)
                    .addComponent(CCV_error)
                    .addGap(0, 0, 0)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 0, 0)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CardNum_error)
                        .addComponent(CardHolder_error)))
            );
            MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainPanelLayout.createSequentialGroup()
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addGap(107, 107, 107)
                            .addComponent(CardNum_error)
                            .addGap(71, 71, 71)
                            .addComponent(CardHolder_error)
                            .addGap(48, 48, 48)
                            .addComponent(Date_error, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addComponent(CCV_error))
                        .addGroup(MainPanelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                    .addComponent(back)
                    .addGap(35, 35, 35)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    private void Card_numberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card_numberMouseClicked
        Card_number.setBackground(Color.WHITE);
        Card_number.setText("");
    }//GEN-LAST:event_Card_numberMouseClicked

    private void Card_holder_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card_holder_nameMouseClicked
        // TODO add your handling code here:
        Card_holder_name.setBackground(Color.WHITE);
        Card_holder_name.setText("");

    }//GEN-LAST:event_Card_holder_nameMouseClicked

    private void monthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthMouseClicked
        // TODO add your handling code here:
        month.setBackground(Color.WHITE);
        month.setText("");
    }//GEN-LAST:event_monthMouseClicked

    private void YearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YearMouseClicked
        // TODO add your handling code here:
        Year.setBackground(Color.WHITE);
        Year.setText("");
    }//GEN-LAST:event_YearMouseClicked

    private void ccvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccvMouseClicked
        ccv.setBackground(Color.WHITE);
        ccv.setText("");
    }//GEN-LAST:event_ccvMouseClicked

    private void Card_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card_numberActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Card_numberActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        boolean valid = true;
        boolean check = true;
        String CardNumber = Card_number.getText();
        String CardHolderName = Card_holder_name.getText();
        String Month = month.getText();
        String year = Year.getText();
        String CCV = ccv.getText();
        CardNum_error.setText("");
        CardHolder_error.setText("");
        Date_error.setText("");
        CCV_error.setText("");

        //**************************************************************************************************
        if (!CardNumber.isEmpty()) {
            if (CardNumber.length() == 16) {
                for (int i = 0; i < 16; i++) {
                    if (!Character.isDigit(CardNumber.charAt(i)) || CardNumber.length() != 16) {
                        Card_number.setBackground(Color.red);
                        CardNum_error.setText("The Card Number is invalid");
                        valid = false;
                        break;
                    } else {
                        valid = true;
                    }
                }
            } else {
                Card_number.setBackground(Color.red);
                CardNum_error.setText("The Card Number is invalid");
                valid = false;
            }

            //*********************************************************************************************************
            if (!CardHolderName.isEmpty()) {
                valid = true;

            } else {
                CardHolder_error.setText("Card Holder Name is invalid");
                Card_holder_name.setBackground(Color.RED);
                valid = false;
            }
            //***********************************************************************************************************
            if (Month.length() == 2 || Month.length() == 1) {
                for (int i = 0; i < Month.length(); i++) {
                    if (Month.charAt(i) >= '0' && Month.charAt(i) <= '9') {
                        check = true;
                    } else {
                        month.setBackground(Color.red);
                        Date_error.setText("The Month is invalid");
                        valid = false;
                        check = false;
                        break;
                    }
                }
                if (check) {
                    int s = Integer.parseInt(Month);
                    if (s <= 12 && s >= 1) {
                        valid = true;
                    } else {
                        month.setBackground(Color.red);
                        Date_error.setText("The Month is invalid");
                        valid = false;
                    }
                }
            } else {
                month.setBackground(Color.red);
                Date_error.setText("The Month is invalid");
                valid = false;
            }

            //**********************************************************************************************************
            if (!year.isEmpty()) {
                if (year.length() == 4) {
                    for (int i = 0; i < year.length(); i++) {
                        if (year.charAt(i) >= '0' && year.charAt(i) <= '9') {
                            valid = true;
                        } else {
                            Year.setBackground(Color.red);
                            Date_error.setText("The Year is invalid");
                            valid = false;
                            break;
                        }
                    }

                } else {
                    Year.setBackground(Color.red);
                    Date_error.setText("The Year is invalid");
                    valid = false;

                }
            }
            //***********************************************************************************************************
            if (!CCV.isEmpty()) {
                for (int i = 0; i < CCV.length(); i++) {
                    if (CCV.length() != 3 || !Character.isDigit(CCV.charAt(i))) {
                        ccv.setBackground(Color.red);
                        CCV_error.setText("The CCV is invalid");
                        valid = false;
                        break;
                    }
                }
            }
            //*************************************************************************************************************
        }
        if (valid) {
            SuccessPayment SuccessPaymentWindow = new SuccessPayment();
            SuccessPaymentWindow.setVisible(true);
            SuccessPaymentWindow.pack();
            SuccessPaymentWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_paymentActionPerformed

    private void Card_holder_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card_holder_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Card_holder_nameActionPerformed

    private void ccvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccvActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         ReservationDetails RWindow = new ReservationDetails();
        RWindow.setVisible(true);
        RWindow.pack();
        RWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed
   
          

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CCV_error;
    private javax.swing.JLabel CardHolder_error;
    private javax.swing.JLabel CardNum_error;
    private javax.swing.JTextField Card_holder_name;
    private javax.swing.JTextField Card_number;
    private javax.swing.JLabel Date_error;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField Year;
    private javax.swing.JButton back;
    private javax.swing.JTextField ccv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField month;
    private javax.swing.JButton payment;
    // End of variables declaration//GEN-END:variables
}
